services:
  nuxt:
    container_name: nuxt
    image: flapi/website-frontend:develop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV_MODE=local
    command: /bin/sh -c "if [ $$ENV_MODE = 'local' ]; then npx nuxi dev --dotenv .env.development --no-clear --port=1470; else npx nuxi dev --dotenv .env.development-remote --no-clear --port=1470; fi"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '1470:1470'
    networks:
      - app-network

networks:
  app-network:

volumes:
  app:
  node_modules:
