name: 'flapi-cms-designsystem'
services:
  designsystem:
    container_name: designsystem
    image: flapi/designsystem:develop
    restart: always
    build:
      context: ../ # Contexte de build au niveau du parent
      dockerfile: src-app/Dockerfile # Chemin relatif vers le Dockerfile
    environment:
      - ENV_MODE=local
    command: /bin/sh -c "if [ $$ENV_MODE = 'local' ]; then npx nuxi dev --dotenv .env.development --no-clear --port=1470; else npx nuxi dev --dotenv .env.development-remote --no-clear --port=1470; fi"
    volumes:
      - ../:/app # Monter tout le contexte parent
      - /app/node_modules
    ports:
      - '1470:1470'
    networks:
      - app-network
  storybook:
    container_name: storybook
    build:
      context: ../
      dockerfile: Dockerfile.storybook
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - '6400:6400' # Port Storybook
    command: npx storybook dev -p 6400 -c .storybook --no-open
    networks:
      - app-network

networks:
  app-network:
